# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Example-DynamicTableGenerator+CoreData' do
pod 'DynamicTableGenerator'
pod 'PureLayout'
end

target 'Example-DynamicTableGenerator+CoreDataTests' do

end

